Add anvil dependency - test
Fix duplicate cache name in msbuild.yml

Add missing checkout lines of code in msbuild.yml

Add shell in action.yml

try cmd for one run

again..

Try to trigger the use of powershell v7

Add quotation marks in action.yaml

same..

Fix action.yaml

Fix action.yaml

Fix action.yaml

Fix action.yaml

Fix sha in msbuild.yml

Try cache fix

Cache path fix

Use correct key for anvile

Fix anvil cache key again

Add GLEW and GLFW DLLs in artifcat

Add Anvil as dependency in github actions. Squash all trial commits

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -14,10 +14,12 @@ env:
   # Configuration type to build.
   # You can convert this to a build matrix if you need coverage of multiple configuration types.
   # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
+  # Only Release tested!
   BUILD_CONFIGURATION: Release
   BUILD_SHARED: ON
   OUT_DIR: dist
   GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
+  FEANOR_ANVIL_ID: 13937410
   FEANOR_CORE_ID: 11660029
   FEANOR_EXTERNAL_ID: 13987704
   NRI_TAG: v1.100
@@ -27,83 +29,77 @@ jobs:
   build-feanor-core:
     runs-on: windows-2022
     outputs:
-      sha: ${{ steps.core-sha.outputs.sha }}
+      sha: ${{ steps.build.outputs.sha }}
     steps:
-    - name: Get Feanor Core SHA JSON
-      run: |
-        curl --location --output feanor.core.sha --header "PRIVATE-TOKEN: ${{env.GITLAB_TOKEN}}" "https://gitlab.com/api/v4/projects/${{env.FEANOR_CORE_ID}}/repository/commits/master"
-    
-    - name: Read Feanor Core Commit SHA JSON to Variable
-      id: read-core-sha
-      uses: juliangruber/read-file-action@v1.1.7
+    - uses: actions/checkout@v4.1.2
+    - name: Build Feanor Core
+      id: build
+      uses: ./.github/actions/build-feanor
       with:
-        path: feanor.core.sha
-    
-    - name: Set output Feanor Core SHA
-      id: core-sha
-      run: echo "sha=${{ fromJson(steps.read-core-sha.outputs.content).id }}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf-8 -Append
+        component: 'core'
+        repo_id: ${{ env.FEANOR_CORE_ID }}
+        install_path: installed-core
         
+  build-feanor-external:
+    runs-on: windows-2022
+    outputs:
+      sha: ${{ steps.build.outputs.sha }}
+    steps:
+    - uses: actions/checkout@v4.1.2
+    - name: Build Feanor External
+      id: build
+      uses: ./.github/actions/build-feanor
+      with:
+        component: 'external'
+        repo_id: ${{ env.FEANOR_EXTERNAL_ID }}
+        install_path: installed-external
+        submodules: true
+
+  build-feanor-anvil:
+    runs-on: windows-2022
+    needs: [build-feanor-core, build-feanor-external]
+    outputs:
+      sha: ${{ steps.build.outputs.sha }}
+    steps:
+    - uses: actions/checkout@v4.1.2
+    # Get cache contents
     - name: Cache Feanor Core
       id: cache-core
       uses: actions/cache@v4.0.2
       with:
         path: installed-core
-        key: feanor-core-${{ steps.core-sha.outputs.sha }}
-    
-    - name: Get Feanor Core Repo
-      if: steps.cache-core.outputs.cache-hit != 'true'
-      run: |
-        git clone https://oauth2:${{env.GITLAB_TOKEN}}@gitlab.com/cgvg/feanor/core feanor-core
-        cd feanor-core
-        git checkout ${{ steps.core-sha.outputs.sha }}
-        cd ..
-    
-    - name: Build and install Feanor Core
-      if: steps.cache-core.outputs.cache-hit != 'true'
-      run: |
-        cmake -S feanor-core -B feanor-core/build -DCMAKE_INSTALL_PREFIX:PATH="${{github.workspace}}\installed-core" -DBUILD_SHARED_LIBS:BOOL=${{env.BUILD_SHARED}}
-        cmake --build feanor-core/build --config ${{env.BUILD_CONFIGURATION}} --parallel --target install
-        
-  build-feanor-external:
-    runs-on: windows-2022
-    outputs:
-      sha: ${{ steps.external-sha.outputs.sha }}
-    steps:
-    - name: Get Feanor External Commit SHA
-      run: |
-        curl --location --output feanor.external.sha --header "PRIVATE-TOKEN: ${{env.GITLAB_TOKEN}}" "https://gitlab.com/api/v4/projects/${{env.FEANOR_EXTERNAL_ID}}/repository/commits/master"
+        key: feanor-core-${{ needs.build-feanor-core.outputs.sha }}
 
-    - name: Read Feanor External Commit SHA to Variable
-      id: read-external-sha
-      uses: juliangruber/read-file-action@v1.1.7
-      with:
-        path: feanor.external.sha
-        
-    - name: Set output Feanor External SHA
-      id: external-sha
-      run: echo "sha=${{ fromJson(steps.read-external-sha.outputs.content).id }}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf-8 -Append
-      
     - name: Cache Feanor External
       id: cache-external
       uses: actions/cache@v4.0.2
       with:
         path: installed-external
-        key: feanor-external-${{ steps.external-sha.outputs.sha }}
-        
-    - name: Get Feanor External Repo
-      if: steps.cache-external.outputs.cache-hit != 'true'
+        key: feanor-external-${{ needs.build-feanor-external.outputs.sha }}
+
+    # Validate all caches present
+    - name: Validate all caches present
+      if: steps.cache-core.outputs.cache-hit != 'true' || steps.cache-external.outputs.cache-hit != 'true'
       run: |
-        git clone https://oauth2:${{env.GITLAB_TOKEN}}@gitlab.com/cgvg/feanor/external feanor-external
-        cd feanor-external
-        git checkout ${{ steps.external-sha.outputs.sha }}
-        git submodule update --init --recursive
-        cd ..
-        
-    - name: Build and install Feanor External
-      if: steps.cache-external.outputs.cache-hit != 'true'
-      working-directory: ${{github.workspace}}\feanor-external
+        echo "Validation failed. There is a missing cache"
+        exit 1
+    
+    # Merge dirs
+    - name: Merge dependency directories into installed directory
       run: |
-        .\install.ps1 "${{github.workspace}}\installed-external" ${{env.BUILD_SHARED}}
+        New-Item installed -ItemType Directory
+        Copy-Item -Path installed-core\* -Destination installed -Recurse -Force
+        Copy-Item -Path installed-external\* -Destination installed -Recurse -Force
+      
+    - name: Build Feanor Anvil
+      id: build
+      uses: ./.github/actions/build-feanor
+      with:
+        component: 'anvil'
+        repo_id: ${{ env.FEANOR_ANVIL_ID }}
+        prefix_path: installed
+        append_key: '-${{ needs.build-feanor-core.outputs.sha }}-${{ needs.build-feanor-external.outputs.sha }}'
+        install_path: installed-anvil
         
   build-nvidia-nri:
     runs-on: windows-2022
@@ -204,7 +200,7 @@ jobs:
   
   build:
     runs-on: windows-2022
-    needs: [build-feanor-core, build-feanor-external, build-nvidia-nri, build-nvidia-nrd]
+    needs: [build-feanor-core, build-feanor-external, build-feanor-anvil, build-nvidia-nri, build-nvidia-nrd]
     steps:
     - uses: actions/checkout@v4.1.2
     
@@ -223,6 +219,13 @@ jobs:
         path: installed-external
         key: feanor-external-${{ needs.build-feanor-external.outputs.sha }}
 
+    - name: Cache Feanor Anvil
+      id: cache-anvil
+      uses: actions/cache@v4.0.2
+      with:
+        path: installed-anvil
+        key: feanor-anvil-${{ needs.build-feanor-anvil.outputs.sha }}-${{ needs.build-feanor-core.outputs.sha }}-${{ needs.build-feanor-external.outputs.sha }}
+
     - name: Cache NVIDIA NRI
       id: cache-nri
       uses: actions/cache@v4.0.2
@@ -239,7 +242,7 @@ jobs:
     
     # Validate all caches present
     - name: Validate all caches present
-      if: steps.cache-core.outputs.cache-hit != 'true' || steps.cache-external.outputs.cache-hit != 'true' || steps.cache-nri.outputs.cache-hit != 'true' || steps.cache-nrd.outputs.cache-hit != 'true'
+      if: steps.cache-core.outputs.cache-hit != 'true' || steps.cache-external.outputs.cache-hit != 'true' || steps.cache-anvil.outputs.cache-hit != 'true' || steps.cache-nri.outputs.cache-hit != 'true' || steps.cache-nrd.outputs.cache-hit != 'true'
       run: |
         echo "Validation failed. There is a missing cache"
         exit 1
@@ -250,6 +253,7 @@ jobs:
         New-Item installed -ItemType Directory
         Copy-Item -Path installed-core\* -Destination installed -Recurse -Force
         Copy-Item -Path installed-external\* -Destination installed -Recurse -Force
+        Copy-Item -Path installed-anvil\* -Destination installed -Recurse -Force
     
     - name: Add FEANOR_ROOT Environment Variable
       run: echo "FEANOR_ROOT=${{github.workspace}}\installed" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
@@ -273,6 +277,9 @@ jobs:
       if: env.BUILD_SHARED == 'ON'
       run: |
         Copy-Item ".\installed\bin\Core.dll" -Destination "${{github.workspace}}\${{env.OUT_DIR}}\"
+        Copy-Item ".\installed\bin\Anvil.dll" -Destination "${{github.workspace}}\${{env.OUT_DIR}}\"
+        Copy-Item ".\installed\bin\glew32.dll" -Destination "${{github.workspace}}\${{env.OUT_DIR}}\"
+        Copy-Item ".\installed\bin\glfw3.dll" -Destination "${{github.workspace}}\${{env.OUT_DIR}}\"
         Copy-Item ".\installed\bin\assimp-vc143-mt.dll" -Destination "${{github.workspace}}\${{env.OUT_DIR}}\"
         Copy-Item ".\installed\bin\imgui.dll" -Destination "${{github.workspace}}\${{env.OUT_DIR}}\"
         Copy-Item ".\installed\bin\stb.dll" -Destination "${{github.workspace}}\${{env.OUT_DIR}}\"
